// Auto-generated block mappings - 完整版
var BEDROCK_ID_MAP = {
 // ===== 石头类 =====
 "minecraft:stone": "stone",
 "minecraft:granite": "granite",
 "minecraft:polished_granite": "granite 1",
 "minecraft:diorite": "diorite",
 "minecraft:polished_diorite": "diorite 1",
 "minecraft:andesite": "andesite",
 "minecraft:polished_andesite": "andesite 1",
 "minecraft:cobblestone": "cobblestone",
 "minecraft:bedrock": "bedrock",
 "minecraft:mossy_cobblestone": "mossy_cobblestone",
 "minecraft:deepslate": "deepslate",
 "minecraft:cobbled_deepslate": "cobbled_deepslate",
 "minecraft:tuff": "tuff",
 "minecraft:calcite": "calcite",
 "minecraft:dripstone_block": "dripstone_block",
 
 // ===== 泥土类 =====
 "minecraft:dirt": "dirt",
 "minecraft:grass_block": "grass",
 "minecraft:coarse_dirt": "dirt 1",
 "minecraft:podzol": "podzol",
 "minecraft:mycelium": "mycelium",
 "minecraft:moss_block": "moss_block",
 "minecraft:sand": "sand",
 "minecraft:red_sand": "sand 1",
 "minecraft:gravel": "gravel",
 "minecraft:clay": "clay",
 
 // ===== 矿石类 =====
 "minecraft:coal_ore": "coal_ore",
 "minecraft:deepslate_coal_ore": "deepslate_coal_ore",
 "minecraft:iron_ore": "iron_ore",
 "minecraft:deepslate_iron_ore": "deepslate_iron_ore",
 "minecraft:gold_ore": "gold_ore",
 "minecraft:deepslate_gold_ore": "deepslate_gold_ore",
 "minecraft:copper_ore": "copper_ore",
 "minecraft:deepslate_copper_ore": "deepslate_copper_ore",
 "minecraft:redstone_ore": "redstone_ore",
 "minecraft:deepslate_redstone_ore": "deepslate_redstone_ore",
 "minecraft:emerald_ore": "emerald_ore",
 "minecraft:deepslate_emerald_ore": "deepslate_emerald_ore",
 "minecraft:lapis_ore": "lapis_ore",
 "minecraft:deepslate_lapis_ore": "deepslate_lapis_ore",
 "minecraft:diamond_ore": "diamond_ore",
 "minecraft:deepslate_diamond_ore": "deepslate_diamond_ore",
 "minecraft:nether_quartz_ore": "quartz_ore",
 "minecraft:nether_gold_ore": "nether_gold_ore",
 "minecraft:ancient_debris": "ancient_debris",
 
 // ===== 原木类 =====
 "minecraft:oak_log": "oak_log",
 "minecraft:spruce_log": "spruce_log",
 "minecraft:birch_log": "birch_log",
 "minecraft:jungle_log": "jungle_log",
 "minecraft:acacia_log": "acacia_log",
 "minecraft:dark_oak_log": "dark_oak_log",
 "minecraft:mangrove_log": "mangrove_log",
 "minecraft:cherry_log": "cherry_log",
 "minecraft:crimson_stem": "crimson_stem",
 "minecraft:warped_stem": "warped_stem",
 "minecraft:stripped_oak_log": "stripped_oak_log",
 "minecraft:stripped_spruce_log": "stripped_spruce_log",
 "minecraft:stripped_birch_log": "stripped_birch_log",
 "minecraft:stripped_jungle_log": "stripped_jungle_log",
 "minecraft:stripped_acacia_log": "stripped_acacia_log",
 "minecraft:stripped_dark_oak_log": "stripped_dark_oak_log",
 "minecraft:stripped_mangrove_log": "stripped_mangrove_log",
 "minecraft:stripped_cherry_log": "stripped_cherry_log",
 "minecraft:stripped_crimson_stem": "stripped_crimson_stem",
 "minecraft:stripped_warped_stem": "stripped_warped_stem",
 "minecraft:crimson_hyphae": "crimson_hyphae",
 "minecraft:warped_hyphae": "warped_hyphae",
 "minecraft:stripped_crimson_hyphae": "stripped_crimson_hyphae",
 "minecraft:stripped_warped_hyphae": "stripped_warped_hyphae",
 
 // ===== 木板类 =====
 "minecraft:oak_planks": "planks",
 "minecraft:spruce_planks": "planks 1",
 "minecraft:birch_planks": "planks 2",
 "minecraft:jungle_planks": "planks 3",
 "minecraft:acacia_planks": "planks 4",
 "minecraft:dark_oak_planks": "planks 5",
 "minecraft:mangrove_planks": "planks 6",
 "minecraft:cherry_planks": "planks 7",
 "minecraft:crimson_planks": "crimson_planks",
 "minecraft:warped_planks": "warped_planks",
 "minecraft:bamboo_planks": "bamboo_planks",
 
 // ===== 树叶类 =====
 "minecraft:oak_leaves": "oak_leaves",
 "minecraft:spruce_leaves": "spruce_leaves",
 "minecraft:birch_leaves": "birch_leaves",
 "minecraft:jungle_leaves": "jungle_leaves",
 "minecraft:acacia_leaves": "acacia_leaves",
 "minecraft:dark_oak_leaves": "dark_oak_leaves",
 "minecraft:mangrove_leaves": "mangrove_leaves",
 "minecraft:cherry_leaves": "cherry_leaves",
 "minecraft:azalea_leaves": "azalea_leaves",
 "minecraft:flowering_azalea_leaves": "flowering_azalea_leaves",
 
 // ===== 石砖类 =====
 "minecraft:stone_bricks": "stone_bricks",
 "minecraft:mossy_stone_bricks": "mossy_stone_bricks",
 "minecraft:cracked_stone_bricks": "cracked_stone_bricks",
 "minecraft:chiseled_stone_bricks": "chiseled_stone_bricks",
 "minecraft:bricks": "brick_block",
 "minecraft:nether_bricks": "nether_brick",
 "minecraft:red_nether_bricks": "red_nether_brick",
 "minecraft:end_stone_bricks": "end_stone_bricks",
 "minecraft:deepslate_tiles": "deepslate_tiles",
 "minecraft:cracked_deepslate_tiles": "cracked_deepslate_tiles",
 "minecraft:deepslate_bricks": "deepslate_bricks",
 "minecraft:cracked_deepslate_bricks": "cracked_deepslate_bricks",
 "minecraft:chiseled_deepslate": "chiseled_deepslate",
 "minecraft:polished_deepslate": "polished_deepslate",
 "minecraft:reinforced_deepslate": "reinforced_deepslate",
 "minecraft:infested_deepslate": "infested_deepslate",
 
 // ===== 玻璃类 =====
 "minecraft:glass": "glass",
 "minecraft:glass_pane": "glass_pane",
 "minecraft:white_stained_glass": "white_stained_glass",
 "minecraft:orange_stained_glass": "orange_stained_glass",
 "minecraft:magenta_stained_glass": "magenta_stained_glass",
 "minecraft:light_blue_stained_glass": "light_blue_stained_glass",
 "minecraft:yellow_stained_glass": "yellow_stained_glass",
 "minecraft:lime_stained_glass": "lime_stained_glass",
 "minecraft:pink_stained_glass": "pink_stained_glass",
 "minecraft:gray_stained_glass": "gray_stained_glass",
 "minecraft:light_gray_stained_glass": "light_gray_stained_glass",
 "minecraft:cyan_stained_glass": "cyan_stained_glass",
 "minecraft:purple_stained_glass": "purple_stained_glass",
 "minecraft:blue_stained_glass": "blue_stained_glass",
 "minecraft:brown_stained_glass": "brown_stained_glass",
 "minecraft:green_stained_glass": "green_stained_glass",
 "minecraft:red_stained_glass": "red_stained_glass",
 "minecraft:black_stained_glass": "black_stained_glass",
 "minecraft:tinted_glass": "tinted_glass",
 
 // ===== 玻璃板类 =====
 "minecraft:white_stained_glass_pane": "white_stained_glass_pane",
 "minecraft:orange_stained_glass_pane": "orange_stained_glass_pane",
 "minecraft:magenta_stained_glass_pane": "magenta_stained_glass_pane",
 "minecraft:light_blue_stained_glass_pane": "light_blue_stained_glass_pane",
 "minecraft:yellow_stained_glass_pane": "yellow_stained_glass_pane",
 "minecraft:lime_stained_glass_pane": "lime_stained_glass_pane",
 "minecraft:pink_stained_glass_pane": "pink_stained_glass_pane",
 "minecraft:gray_stained_glass_pane": "gray_stained_glass_pane",
 "minecraft:light_gray_stained_glass_pane": "light_gray_stained_glass_pane",
 "minecraft:cyan_stained_glass_pane": "cyan_stained_glass_pane",
 "minecraft:purple_stained_glass_pane": "purple_stained_glass_pane",
 "minecraft:blue_stained_glass_pane": "blue_stained_glass_pane",
 "minecraft:brown_stained_glass_pane": "brown_stained_glass_pane",
 "minecraft:green_stained_glass_pane": "green_stained_glass_pane",
 "minecraft:red_stained_glass_pane": "red_stained_glass_pane",
 "minecraft:black_stained_glass_pane": "black_stained_glass_pane",
 
 // ===== 羊毛类 =====
 "minecraft:white_wool": "wool",
 "minecraft:orange_wool": "wool 1",
 "minecraft:magenta_wool": "wool 2",
 "minecraft:light_blue_wool": "wool 3",
 "minecraft:yellow_wool": "wool 4",
 "minecraft:lime_wool": "wool 5",
 "minecraft:pink_wool": "wool 6",
 "minecraft:gray_wool": "wool 7",
 "minecraft:light_gray_wool": "wool 8",
 "minecraft:cyan_wool": "wool 9",
 "minecraft:purple_wool": "wool 10",
 "minecraft:blue_wool": "wool 11",
 "minecraft:brown_wool": "wool 12",
 "minecraft:green_wool": "wool 13",
 "minecraft:red_wool": "wool 14",
 "minecraft:black_wool": "wool 15",
 
 // ===== 地毯类 =====
 "minecraft:white_carpet": "white_carpet",
 "minecraft:orange_carpet": "orange_carpet",
 "minecraft:magenta_carpet": "magenta_carpet",
 "minecraft:light_blue_carpet": "light_blue_carpet",
 "minecraft:yellow_carpet": "yellow_carpet",
 "minecraft:lime_carpet": "lime_carpet",
 "minecraft:pink_carpet": "pink_carpet",
 "minecraft:gray_carpet": "gray_carpet",
 "minecraft:light_gray_carpet": "light_gray_carpet",
 "minecraft:cyan_carpet": "cyan_carpet",
 "minecraft:purple_carpet": "purple_carpet",
 "minecraft:blue_carpet": "blue_carpet",
 "minecraft:brown_carpet": "brown_carpet",
 "minecraft:green_carpet": "green_carpet",
 "minecraft:red_carpet": "red_carpet",
 "minecraft:black_carpet": "black_carpet",
 
 // ===== 矿物块类 =====
 "minecraft:coal_block": "coal_block",
 "minecraft:iron_block": "iron_block",
 "minecraft:gold_block": "gold_block",
 "minecraft:diamond_block": "diamond_block",
 "minecraft:emerald_block": "emerald_block",
 "minecraft:redstone_block": "redstone_block",
 "minecraft:lapis_block": "lapis_block",
 "minecraft:copper_block": "copper_block",
 "minecraft:exposed_copper": "exposed_copper",
 "minecraft:weathered_copper": "weathered_copper",
 "minecraft:oxidized_copper": "oxidized_copper",
 "minecraft:cut_copper": "cut_copper",
 "minecraft:exposed_cut_copper": "exposed_cut_copper",
 "minecraft:weathered_cut_copper": "weathered_cut_copper",
 "minecraft:oxidized_cut_copper": "oxidized_cut_copper",
 "minecraft:raw_iron_block": "raw_iron_block",
 "minecraft:raw_copper_block": "raw_copper_block",
 "minecraft:raw_gold_block": "raw_gold_block",
 "minecraft:netherite_block": "netherite_block",
 
 // ===== 下界类 =====
 "minecraft:netherrack": "netherrack",
 "minecraft:soul_sand": "soul_sand",
 "minecraft:soul_soil": "soul_soil",
 "minecraft:basalt": "basalt",
 "minecraft:polished_basalt": "polished_basalt",
 "minecraft:smooth_basalt": "smooth_basalt",
 "minecraft:blackstone": "blackstone",
 "minecraft:gilded_blackstone": "gilded_blackstone",
 "minecraft:polished_blackstone": "polished_blackstone",
 "minecraft:polished_blackstone_bricks": "polished_blackstone_bricks",
 "minecraft:cracked_polished_blackstone_bricks": "cracked_polished_blackstone_bricks",
 "minecraft:chiseled_polished_blackstone": "chiseled_polished_blackstone",
 "minecraft:magma_block": "magma",
 "minecraft:glowstone": "glowstone",
 "minecraft:shroomlight": "shroomlight",
 "minecraft:crimson_nylium": "crimson_nylium",
 "minecraft:warped_nylium": "warped_nylium",
 
 // ===== 末地类 =====
 "minecraft:end_stone": "end_stone",
 "minecraft:purpur_block": "purpur_block",
 "minecraft:purpur_pillar": "purpur_pillar",
 "minecraft:purpur_stairs": "purpur_stairs",
 "minecraft:purpur_slab": "purpur_slab",
 
 // ===== 液体类 =====
 "minecraft:water": "water",
 "minecraft:lava": "lava",
 
 // ===== 冰类 =====
 "minecraft:ice": "ice",
 "minecraft:packed_ice": "packed_ice",
 "minecraft:blue_ice": "blue_ice",
 "minecraft:snow": "snow",
 "minecraft:snow_block": "snow_layer",
 
 // ===== 黑曜石类 =====
 "minecraft:obsidian": "obsidian",
 "minecraft:crying_obsidian": "crying_obsidian",
 
 // ===== 海绵类 =====
 "minecraft:sponge": "sponge",
 "minecraft:wet_sponge": "sponge 1",
 
 // ===== 特殊方块 =====
 "minecraft:slime_block": "slime",
 "minecraft:honey_block": "honey_block",
 "minecraft:bone_block": "bone_block",
 "minecraft:quartz_block": "quartz_block",
 "minecraft:quartz_pillar": "quartz_pillar",
 "minecraft:chiseled_quartz": "chiseled_quartz_block",
 "minecraft:amethyst_block": "amethyst_block",
 "minecraft:budding_amethyst": "budding_amethyst",
 "minecraft:amethyst_cluster": "amethyst_cluster",
 "minecraft:large_amethyst_bud": "large_amethyst_bud",
 "minecraft:medium_amethyst_bud": "medium_amethyst_bud",
 "minecraft:small_amethyst_bud": "small_amethyst_bud",
 
 // ===== 陶瓦类 =====
 "minecraft:terracotta": "terracotta",
 "minecraft:white_terracotta": "terracotta 0",
 "minecraft:orange_terracotta": "terracotta 1",
 "minecraft:magenta_terracotta": "terracotta 2",
 "minecraft:light_blue_terracotta": "terracotta 3",
 "minecraft:yellow_terracotta": "terracotta 4",
 "minecraft:lime_terracotta": "terracotta 5",
 "minecraft:pink_terracotta": "terracotta 6",
 "minecraft:gray_terracotta": "terracotta 7",
 "minecraft:light_gray_terracotta": "terracotta 8",
 "minecraft:cyan_terracotta": "terracotta 9",
 "minecraft:purple_terracotta": "terracotta 10",
 "minecraft:blue_terracotta": "terracotta 11",
 "minecraft:brown_terracotta": "terracotta 12",
 "minecraft:green_terracotta": "terracotta 13",
 "minecraft:red_terracotta": "terracotta 14",
 "minecraft:black_terracotta": "terracotta 15",
 
 // ===== 带釉陶瓦类 =====
 "minecraft:white_glazed_terracotta": "white_glazed_terracotta",
 "minecraft:orange_glazed_terracotta": "orange_glazed_terracotta",
 "minecraft:magenta_glazed_terracotta": "magenta_glazed_terracotta",
 "minecraft:light_blue_glazed_terracotta": "light_blue_glazed_terracotta",
 "minecraft:yellow_glazed_terracotta": "yellow_glazed_terracotta",
 "minecraft:lime_glazed_terracotta": "lime_glazed_terracotta",
 "minecraft:pink_glazed_terracotta": "pink_glazed_terracotta",
 "minecraft:gray_glazed_terracotta": "gray_glazed_terracotta",
 "minecraft:light_gray_glazed_terracotta": "light_gray_glazed_terracotta",
 "minecraft:cyan_glazed_terracotta": "cyan_glazed_terracotta",
 "minecraft:purple_glazed_terracotta": "purple_glazed_terracotta",
 "minecraft:blue_glazed_terracotta": "blue_glazed_terracotta",
 "minecraft:brown_glazed_terracotta": "brown_glazed_terracotta",
 "minecraft:green_glazed_terracotta": "green_glazed_terracotta",
 "minecraft:red_glazed_terracotta": "red_glazed_terracotta",
 "minecraft:black_glazed_terracotta": "black_glazed_terracotta",
 
 // ===== 混凝土类 =====
 "minecraft:concrete": "concrete",
 "minecraft:white_concrete": "concrete 0",
 "minecraft:orange_concrete": "concrete 1",
 "minecraft:magenta_concrete": "concrete 2",
 "minecraft:light_blue_concrete": "concrete 3",
 "minecraft:yellow_concrete": "concrete 4",
 "minecraft:lime_concrete": "concrete 5",
 "minecraft:pink_concrete": "concrete 6",
 "minecraft:gray_concrete": "concrete 7",
 "minecraft:light_gray_concrete": "concrete 8",
 "minecraft:cyan_concrete": "concrete 9",
 "minecraft:purple_concrete": "concrete 10",
 "minecraft:blue_concrete": "concrete 11",
 "minecraft:brown_concrete": "concrete 12",
 "minecraft:green_concrete": "concrete 13",
 "minecraft:red_concrete": "concrete 14",
 "minecraft:black_concrete": "concrete 15",
 
 // ===== 混凝土粉末类 =====
 "minecraft:white_concrete_powder": "white_concrete_powder",
 "minecraft:orange_concrete_powder": "orange_concrete_powder",
 "minecraft:magenta_concrete_powder": "magenta_concrete_powder",
 "minecraft:light_blue_concrete_powder": "light_blue_concrete_powder",
 "minecraft:yellow_concrete_powder": "yellow_concrete_powder",
 "minecraft:lime_concrete_powder": "lime_concrete_powder",
 "minecraft:pink_concrete_powder": "pink_concrete_powder",
 "minecraft:gray_concrete_powder": "gray_concrete_powder",
 "minecraft:light_gray_concrete_powder": "light_gray_concrete_powder",
 "minecraft:cyan_concrete_powder": "cyan_concrete_powder",
 "minecraft:purple_concrete_powder": "purple_concrete_powder",
 "minecraft:blue_concrete_powder": "blue_concrete_powder",
 "minecraft:brown_concrete_powder": "brown_concrete_powder",
 "minecraft:green_concrete_powder": "green_concrete_powder",
 "minecraft:red_concrete_powder": "red_concrete_powder",
 "minecraft:black_concrete_powder": "black_concrete_powder",
 
 // ===== 楼梯类 =====
 "minecraft:oak_stairs": "oak_stairs",
 "minecraft:spruce_stairs": "spruce_stairs",
 "minecraft:birch_stairs": "birch_stairs",
 "minecraft:jungle_stairs": "jungle_stairs",
 "minecraft:acacia_stairs": "acacia_stairs",
 "minecraft:dark_oak_stairs": "dark_oak_stairs",
 "minecraft:mangrove_stairs": "mangrove_stairs",
 "minecraft:cherry_stairs": "cherry_stairs",
 "minecraft:bamboo_stairs": "bamboo_stairs",
 "minecraft:crimson_stairs": "crimson_stairs",
 "minecraft:warped_stairs": "warped_stairs",
 "minecraft:stone_stairs": "stone_stairs",
 "minecraft:cobblestone_stairs": "cobblestone_stairs",
 "minecraft:mossy_cobblestone_stairs": "mossy_cobblestone_stairs",
 "minecraft:stone_brick_stairs": "stone_brick_stairs",
 "minecraft:mossy_stone_brick_stairs": "mossy_stone_brick_stairs",
 "minecraft:andesite_stairs": "andesite_stairs",
 "minecraft:polished_andesite_stairs": "polished_andesite_stairs",
 "minecraft:diorite_stairs": "diorite_stairs",
 "minecraft:polished_diorite_stairs": "polished_diorite_stairs",
 "minecraft:granite_stairs": "granite_stairs",
 "minecraft:polished_granite_stairs": "polished_granite_stairs",
 "minecraft:sandstone_stairs": "sandstone_stairs",
 "minecraft:smooth_sandstone_stairs": "smooth_sandstone_stairs",
 "minecraft:red_sandstone_stairs": "red_sandstone_stairs",
 "minecraft:smooth_red_sandstone_stairs": "smooth_red_sandstone_stairs",
 "minecraft:brick_stairs": "brick_stairs",
 "minecraft:mud_brick_stairs": "mud_brick_stairs",
 "minecraft:nether_brick_stairs": "nether_brick_stairs",
 "minecraft:red_nether_brick_stairs": "red_nether_brick_stairs",
 "minecraft:quartz_stairs": "quartz_stairs",
 "minecraft:smooth_quartz_stairs": "smooth_quartz_stairs",
 "minecraft:prismarine_stairs": "prismarine_stairs",
 "minecraft:prismarine_brick_stairs": "prismarine_brick_stairs",
 "minecraft:dark_prismarine_stairs": "dark_prismarine_stairs",
 "minecraft:blackstone_stairs": "blackstone_stairs",
 "minecraft:polished_blackstone_stairs": "polished_blackstone_stairs",
 "minecraft:polished_blackstone_brick_stairs": "polished_blackstone_brick_stairs",
 "minecraft:end_stone_brick_stairs": "end_stone_brick_stairs",
 "minecraft:deepslate_tile_stairs": "deepslate_tile_stairs",
 "minecraft:deepslate_brick_stairs": "deepslate_brick_stairs",
 "minecraft:cobbled_deepslate_stairs": "cobbled_deepslate_stairs",
 "minecraft:polished_deepslate_stairs": "polished_deepslate_stairs",
 "minecraft:cut_copper_stairs": "cut_copper_stairs",
 "minecraft:exposed_cut_copper_stairs": "exposed_cut_copper_stairs",
 "minecraft:weathered_cut_copper_stairs": "weathered_cut_copper_stairs",
 "minecraft:oxidized_cut_copper_stairs": "oxidized_cut_copper_stairs",
 "minecraft:waxed_cut_copper_stairs": "waxed_cut_copper_stairs",
 "minecraft:waxed_exposed_cut_copper_stairs": "waxed_exposed_cut_copper_stairs",
 "minecraft:waxed_weathered_cut_copper_stairs": "waxed_weathered_cut_copper_stairs",
 "minecraft:waxed_oxidized_cut_copper_stairs": "waxed_oxidized_cut_copper_stairs",
 "minecraft:bamboo_mosaic_stairs": "bamboo_mosaic_stairs",
 
 // ===== 台阶类 =====
 "minecraft:oak_slab": "oak_slab",
 "minecraft:spruce_slab": "spruce_slab",
 "minecraft:birch_slab": "birch_slab",
 "minecraft:jungle_slab": "jungle_slab",
 "minecraft:acacia_slab": "acacia_slab",
 "minecraft:dark_oak_slab": "dark_oak_slab",
 "minecraft:mangrove_slab": "mangrove_slab",
 "minecraft:cherry_slab": "cherry_slab",
 "minecraft:bamboo_slab": "bamboo_slab",
 "minecraft:crimson_slab": "crimson_slab",
 "minecraft:warped_slab": "warped_slab",
 "minecraft:stone_slab": "stone_slab",
 "minecraft:cobblestone_slab": "cobblestone_slab",
 "minecraft:mossy_cobblestone_slab": "mossy_cobblestone_slab",
 "minecraft:stone_brick_slab": "stone_brick_slab",
 "minecraft:mossy_stone_brick_slab": "mossy_stone_brick_slab",
 "minecraft:andesite_slab": "andesite_slab",
 "minecraft:polished_andesite_slab": "polished_andesite_slab",
 "minecraft:diorite_slab": "diorite_slab",
 "minecraft:polished_diorite_slab": "polished_diorite_slab",
 "minecraft:granite_slab": "granite_slab",
 "minecraft:polished_granite_slab": "polished_granite_slab",
 "minecraft:sandstone_slab": "sandstone_slab",
 "minecraft:cut_sandstone_slab": "cut_sandstone_slab",
 "minecraft:smooth_sandstone_slab": "smooth_sandstone_slab",
 "minecraft:red_sandstone_slab": "red_sandstone_slab",
 "minecraft:cut_red_sandstone_slab": "cut_red_sandstone_slab",
 "minecraft:smooth_red_sandstone_slab": "smooth_red_sandstone_slab",
 "minecraft:brick_slab": "brick_slab",
 "minecraft:mud_brick_slab": "mud_brick_slab",
 "minecraft:nether_brick_slab": "nether_brick_slab",
 "minecraft:red_nether_brick_slab": "red_nether_brick_slab",
 "minecraft:quartz_slab": "quartz_slab",
 "minecraft:smooth_quartz_slab": "smooth_quartz_slab",
 "minecraft:prismarine_slab": "prismarine_slab",
 "minecraft:prismarine_brick_slab": "prismarine_brick_slab",
 "minecraft:dark_prismarine_slab": "dark_prismarine_slab",
 "minecraft:blackstone_slab": "blackstone_slab",
 "minecraft:polished_blackstone_slab": "polished_blackstone_slab",
 "minecraft:polished_blackstone_brick_slab": "polished_blackstone_brick_slab",
 "minecraft:end_stone_brick_slab": "end_stone_brick_slab",
 "minecraft:deepslate_tile_slab": "deepslate_tile_slab",
 "minecraft:deepslate_brick_slab": "deepslate_brick_slab",
 "minecraft:cobbled_deepslate_slab": "cobbled_deepslate_slab",
 "minecraft:polished_deepslate_slab": "polished_deepslate_slab",
 "minecraft:cut_copper_slab": "cut_copper_slab",
 "minecraft:exposed_cut_copper_slab": "exposed_cut_copper_slab",
 "minecraft:weathered_cut_copper_slab": "weathered_cut_copper_slab",
 "minecraft:oxidized_cut_copper_slab": "oxidized_cut_copper_slab",
 "minecraft:waxed_cut_copper_slab": "waxed_cut_copper_slab",
 "minecraft:waxed_exposed_cut_copper_slab": "waxed_exposed_cut_copper_slab",
 "minecraft:waxed_weathered_cut_copper_slab": "waxed_weathered_cut_copper_slab",
 "minecraft:waxed_oxidized_cut_copper_slab": "waxed_oxidized_cut_copper_slab",
 "minecraft:bamboo_mosaic_slab": "bamboo_mosaic_slab",
 
 // ===== 栅栏类 =====
 "minecraft:oak_fence": "oak_fence",
 "minecraft:spruce_fence": "spruce_fence",
 "minecraft:birch_fence": "birch_fence",
 "minecraft:jungle_fence": "jungle_fence",
 "minecraft:acacia_fence": "acacia_fence",
 "minecraft:dark_oak_fence": "dark_oak_fence",
 "minecraft:mangrove_fence": "mangrove_fence",
 "minecraft:cherry_fence": "cherry_fence",
 "minecraft:bamboo_fence": "bamboo_fence",
 "minecraft:crimson_fence": "crimson_fence",
 "minecraft:warped_fence": "warped_fence",
 "minecraft:nether_brick_fence": "nether_brick_fence",
 
 // ===== 栅栏门类 =====
 "minecraft:oak_fence_gate": "oak_fence_gate",
 "minecraft:spruce_fence_gate": "spruce_fence_gate",
 "minecraft:birch_fence_gate": "birch_fence_gate",
 "minecraft:jungle_fence_gate": "jungle_fence_gate",
 "minecraft:acacia_fence_gate": "acacia_fence_gate",
 "minecraft:dark_oak_fence_gate": "dark_oak_fence_gate",
 "minecraft:mangrove_fence_gate": "mangrove_fence_gate",
 "minecraft:cherry_fence_gate": "cherry_fence_gate",
 "minecraft:bamboo_fence_gate": "bamboo_fence_gate",
 "minecraft:crimson_fence_gate": "crimson_fence_gate",
 "minecraft:warped_fence_gate": "warped_fence_gate",
 
 // ===== 墙类 =====
 "minecraft:cobblestone_wall": "cobblestone_wall",
 "minecraft:mossy_cobblestone_wall": "mossy_cobblestone_wall",
 "minecraft:stone_brick_wall": "stone_brick_wall",
 "minecraft:mossy_stone_brick_wall": "mossy_stone_brick_wall",
 "minecraft:andesite_wall": "andesite_wall",
 "minecraft:diorite_wall": "diorite_wall",
 "minecraft:granite_wall": "granite_wall",
 "minecraft:sandstone_wall": "sandstone_wall",
 "minecraft:red_sandstone_wall": "red_sandstone_wall",
 "minecraft:brick_wall": "brick_wall",
 "minecraft:mud_brick_wall": "mud_brick_wall",
 "minecraft:nether_brick_wall": "nether_brick_wall",
 "minecraft:red_nether_brick_wall": "red_nether_brick_wall",
 "minecraft:end_stone_brick_wall": "end_stone_brick_wall",
 "minecraft:prismarine_wall": "prismarine_wall",
 "minecraft:blackstone_wall": "blackstone_wall",
 "minecraft:polished_blackstone_wall": "polished_blackstone_wall",
 "minecraft:polished_blackstone_brick_wall": "polished_blackstone_brick_wall",
 "minecraft:deepslate_tile_wall": "deepslate_tile_wall",
 "minecraft:deepslate_brick_wall": "deepslate_brick_wall",
 "minecraft:cobbled_deepslate_wall": "cobbled_deepslate_wall",
 "minecraft:polished_deepslate_wall": "polished_deepslate_wall",
 
 // ===== 门类 =====
 "minecraft:oak_door": "oak_door",
 "minecraft:spruce_door": "spruce_door",
 "minecraft:birch_door": "birch_door",
 "minecraft:jungle_door": "jungle_door",
 "minecraft:acacia_door": "acacia_door",
 "minecraft:dark_oak_door": "dark_oak_door",
 "minecraft:mangrove_door": "mangrove_door",
 "minecraft:cherry_door": "cherry_door",
 "minecraft:bamboo_door": "bamboo_door",
 "minecraft:crimson_door": "crimson_door",
 "minecraft:warped_door": "warped_door",
 "minecraft:iron_door": "iron_door",
 
 // ===== 活板门类 =====
 "minecraft:oak_trapdoor": "trapdoor",
 "minecraft:spruce_trapdoor": "trapdoor",
 "minecraft:birch_trapdoor": "trapdoor",
 "minecraft:jungle_trapdoor": "trapdoor",
 "minecraft:acacia_trapdoor": "trapdoor",
 "minecraft:dark_oak_trapdoor": "trapdoor",
 "minecraft:mangrove_trapdoor": "trapdoor",
 "minecraft:cherry_trapdoor": "trapdoor",
 "minecraft:bamboo_trapdoor": "trapdoor",
 "minecraft:crimson_trapdoor": "trapdoor",
 "minecraft:warped_trapdoor": "trapdoor",
 "minecraft:iron_trapdoor": "iron_trapdoor",
 
 // ===== 按钮类 =====
 "minecraft:oak_button": "oak_button",
 "minecraft:spruce_button": "spruce_button",
 "minecraft:birch_button": "birch_button",
 "minecraft:jungle_button": "jungle_button",
 "minecraft:acacia_button": "acacia_button",
 "minecraft:dark_oak_button": "dark_oak_button",
 "minecraft:mangrove_button": "mangrove_button",
 "minecraft:cherry_button": "cherry_button",
 "minecraft:bamboo_button": "bamboo_button",
 "minecraft:crimson_button": "crimson_button",
 "minecraft:warped_button": "warped_button",
 "minecraft:stone_button": "stone_button",
 "minecraft:polished_blackstone_button": "polished_blackstone_button",
 
 // ===== 压力板类 =====
 "minecraft:oak_pressure_plate": "oak_pressure_plate",
 "minecraft:spruce_pressure_plate": "spruce_pressure_plate",
 "minecraft:birch_pressure_plate": "birch_pressure_plate",
 "minecraft:jungle_pressure_plate": "jungle_pressure_plate",
 "minecraft:acacia_pressure_plate": "acacia_pressure_plate",
 "minecraft:dark_oak_pressure_plate": "dark_oak_pressure_plate",
 "minecraft:mangrove_pressure_plate": "mangrove_pressure_plate",
 "minecraft:cherry_pressure_plate": "cherry_pressure_plate",
 "minecraft:bamboo_pressure_plate": "bamboo_pressure_plate",
 "minecraft:crimson_pressure_plate": "crimson_pressure_plate",
 "minecraft:warped_pressure_plate": "warped_pressure_plate",
 "minecraft:stone_pressure_plate": "stone_pressure_plate",
 "minecraft:polished_blackstone_pressure_plate": "polished_blackstone_pressure_plate",
 "minecraft:light_weighted_pressure_plate": "light_weighted_pressure_plate",
 "minecraft:heavy_weighted_pressure_plate": "heavy_weighted_pressure_plate",
 
 // ===== 红石类 =====
 "minecraft:redstone_torch": "redstone_torch",
 "minecraft:redstone_wall_torch": "redstone_torch",
 "minecraft:redstone_lamp": "redstone_lamp",
 "minecraft:piston": "piston",
 "minecraft:sticky_piston": "sticky_piston",
 "minecraft:dispenser": "dispenser",
 "minecraft:dropper": "dropper",
 "minecraft:observer": "observer",
 "minecraft:hopper": "hopper",
 "minecraft:repeater": "repeater",
 "minecraft:comparator": "comparator",
 "minecraft:note_block": "noteblock",
 "minecraft:tnt": "tnt",
 "minecraft:lever": "lever",
 "minecraft:daylight_detector": "daylight_detector",
 "minecraft:tripwire_hook": "tripwire_hook",
 "minecraft:target": "target",
 "minecraft:sculk_sensor": "sculk_sensor",
 "minecraft:calibrated_sculk_sensor": "calibrated_sculk_sensor",
 
 // ===== 光源类 =====
 "minecraft:torch": "torch",
 "minecraft:wall_torch": "torch",
 "minecraft:soul_torch": "soul_torch",
 "minecraft:soul_wall_torch": "soul_torch",
 "minecraft:lantern": "lantern",
 "minecraft:soul_lantern": "soul_lantern",
 "minecraft:sea_lantern": "sea_lantern",
 "minecraft:jack_o_lantern": "jack_o_lantern",
 "minecraft:campfire": "campfire",
 "minecraft:soul_campfire": "soul_campfire",
 "minecraft:candle": "candle",
 "minecraft:white_candle": "white_candle",
 "minecraft:end_rod": "end_rod",
 
 // ===== 青蛙灯类 =====
 "minecraft:froglight": "verdant_froglight",
 "minecraft:pearlescent_froglight": "pearlescent_froglight",
 "minecraft:verdant_froglight": "verdant_froglight",
 "minecraft:ochre_froglight": "ochre_froglight",
 
 // ===== 植物类 =====
 "minecraft:grass": "grass",
 "minecraft:tall_grass": "tallgrass",
 "minecraft:fern": "fern",
 "minecraft:large_fern": "large_fern",
 "minecraft:dead_bush": "deadbush",
 "minecraft:dandelion": "dandelion",
 "minecraft:poppy": "poppy",
 "minecraft:blue_orchid": "blue_orchid",
 "minecraft:allium": "allium",
 "minecraft:azure_bluet": "azure_bluet",
 "minecraft:red_tulip": "red_tulip",
 "minecraft:orange_tulip": "orange_tulip",
 "minecraft:white_tulip": "white_tulip",
 "minecraft:pink_tulip": "pink_tulip",
 "minecraft:oxeye_daisy": "oxeye_daisy",
 "minecraft:cornflower": "cornflower",
 "minecraft:lily_of_the_valley": "lily_of_the_valley",
 "minecraft:wither_rose": "wither_rose",
 "minecraft:sunflower": "sunflower",
 "minecraft:lilac": "lilac",
 "minecraft:rose_bush": "rose_bush",
 "minecraft:peony": "peony",
 "minecraft:lily_pad": "waterlily",
 "minecraft:vine": "vine",
 "minecraft:weeping_vines": "weeping_vines",
 "minecraft:twisting_vines": "twisting_vines",
 "minecraft:cactus": "cactus",
 "minecraft:sugar_cane": "reeds",
 "minecraft:bamboo": "bamboo",
 "minecraft:bamboo_sapling": "bamboo_sapling",
 
 // ===== 蘑菇类 =====
 "minecraft:brown_mushroom": "brown_mushroom",
 "minecraft:red_mushroom": "red_mushroom",
 "minecraft:brown_mushroom_block": "brown_mushroom_block",
 "minecraft:red_mushroom_block": "red_mushroom_block",
 "minecraft:mushroom_stem": "mushroom_stem",
 
 // ===== 下界植物类 =====
 "minecraft:crimson_fungus": "crimson_fungus",
 "minecraft:warped_fungus": "warped_fungus",
 "minecraft:crimson_roots": "crimson_roots",
 "minecraft:warped_roots": "warped_roots",
 "minecraft:nether_sprouts": "nether_sprouts",
 "minecraft:nether_wart": "nether_wart",
 "minecraft:nether_wart_block": "nether_wart_block",
 "minecraft:warped_wart_block": "warped_wart_block",
 
 // ===== 杜鹃花类 =====
 "minecraft:azalea": "azalea",
 "minecraft:flowering_azalea": "flowering_azalea",
 "minecraft:moss_carpet": "moss_carpet",
 "minecraft:big_dripleaf": "big_dripleaf",
 "minecraft:small_dripleaf": "small_dripleaf",
 "minecraft:spore_blossom": "spore_blossom",
 "minecraft:hanging_roots": "hanging_roots",
 "minecraft:glow_lichen": "glow_lichen",
 "minecraft:pink_petals": "pink_petals",
 
 // ===== 树苗类 =====
 "minecraft:oak_sapling": "oak_sapling",
 "minecraft:spruce_sapling": "spruce_sapling",
 "minecraft:birch_sapling": "birch_sapling",
 "minecraft:jungle_sapling": "jungle_sapling",
 "minecraft:acacia_sapling": "acacia_sapling",
 "minecraft:dark_oak_sapling": "dark_oak_sapling",
 "minecraft:mangrove_propagule": "mangrove_propagule",
 "minecraft:cherry_sapling": "cherry_sapling",
 
 // ===== 砂岩类 =====
 "minecraft:sandstone": "sandstone",
 "minecraft:chiseled_sandstone": "chiseled_sandstone",
 "minecraft:cut_sandstone": "cut_sandstone",
 "minecraft:smooth_sandstone": "smooth_sandstone",
 "minecraft:red_sandstone": "red_sandstone",
 "minecraft:chiseled_red_sandstone": "chiseled_red_sandstone",
 "minecraft:cut_red_sandstone": "cut_red_sandstone",
 "minecraft:smooth_red_sandstone": "smooth_red_sandstone",
 
 // ===== 海晶石类 =====
 "minecraft:prismarine": "prismarine",
 "minecraft:prismarine_bricks": "prismarine_bricks",
 "minecraft:dark_prismarine": "dark_prismarine",
 
 // ===== 珊瑚类 =====
 "minecraft:coral_block": "coral_block",
 "minecraft:tube_coral_block": "tube_coral_block",
 "minecraft:brain_coral_block": "brain_coral_block",
 "minecraft:bubble_coral_block": "bubble_coral_block",
 "minecraft:fire_coral_block": "fire_coral_block",
 "minecraft:horn_coral_block": "horn_coral_block",
 "minecraft:tube_coral": "tube_coral",
 "minecraft:brain_coral": "brain_coral",
 "minecraft:bubble_coral": "bubble_coral",
 "minecraft:fire_coral": "fire_coral",
 "minecraft:horn_coral": "horn_coral",
 "minecraft:tube_coral_fan": "tube_coral_fan",
 "minecraft:brain_coral_fan": "brain_coral_fan",
 "minecraft:bubble_coral_fan": "bubble_coral_fan",
 "minecraft:fire_coral_fan": "fire_coral_fan",
 "minecraft:horn_coral_fan": "horn_coral_fan",
 "minecraft:dead_tube_coral_block": "dead_tube_coral_block",
 "minecraft:dead_brain_coral_block": "dead_brain_coral_block",
 "minecraft:dead_bubble_coral_block": "dead_bubble_coral_block",
 "minecraft:dead_fire_coral_block": "dead_fire_coral_block",
 "minecraft:dead_horn_coral_block": "dead_horn_coral_block",
 
 // ===== 干海带块 =====
 "minecraft:dried_kelp_block": "dried_kelp_block",
 
 // ===== 泥浆类 =====
 "minecraft:mud": "mud",
 "minecraft:mud_bricks": "mud_bricks",
 "minecraft:packed_mud": "packed_mud",
 "minecraft:mangrove_roots": "mangrove_roots",
 "minecraft:muddy_mangrove_roots": "muddy_mangrove_roots",
 
 // ===== 竹类 =====
 "minecraft:bamboo_block": "bamboo_block",
 "minecraft:stripped_bamboo_block": "stripped_bamboo_block",
 "minecraft:bamboo_mosaic": "bamboo_mosaic",
 "minecraft:bamboo_wall_sign": "bamboo_wall_sign",
 
 // ===== 功能方块 =====
 "minecraft:bookshelf": "bookshelf",
 "minecraft:brick_block": "brick_block",
 "minecraft:crafting_table": "crafting_table",
 "minecraft:furnace": "furnace",
 "minecraft:blast_furnace": "blast_furnace",
 "minecraft:smoker": "smoker",
 "minecraft:barrel": "barrel",
 "minecraft:chest": "chest",
 "minecraft:trapped_chest": "trapped_chest",
 "minecraft:ender_chest": "ender_chest",
 "minecraft:shulker_box": "shulker_box",
 "minecraft:white_shulker_box": "white_shulker_box",
 "minecraft:orange_shulker_box": "orange_shulker_box",
 "minecraft:magenta_shulker_box": "magenta_shulker_box",
 "minecraft:light_blue_shulker_box": "light_blue_shulker_box",
 "minecraft:yellow_shulker_box": "yellow_shulker_box",
 "minecraft:lime_shulker_box": "lime_shulker_box",
 "minecraft:pink_shulker_box": "pink_shulker_box",
 "minecraft:gray_shulker_box": "gray_shulker_box",
 "minecraft:light_gray_shulker_box": "light_gray_shulker_box",
 "minecraft:cyan_shulker_box": "cyan_shulker_box",
 "minecraft:purple_shulker_box": "purple_shulker_box",
 "minecraft:blue_shulker_box": "blue_shulker_box",
 "minecraft:brown_shulker_box": "brown_shulker_box",
 "minecraft:green_shulker_box": "green_shulker_box",
 "minecraft:red_shulker_box": "red_shulker_box",
 "minecraft:black_shulker_box": "black_shulker_box",
 "minecraft:enchanting_table": "enchanting_table",
 "minecraft:anvil": "anvil",
 "minecraft:chipped_anvil": "chipped_anvil",
 "minecraft:damaged_anvil": "damaged_anvil",
 "minecraft:jukebox": "jukebox",
 "minecraft:lodestone": "lodestone",
 "minecraft:respawn_anchor": "respawn_anchor",
 "minecraft:beacon": "beacon",
 "minecraft:conduit": "conduit",
 "minecraft:scaffolding": "scaffolding",
 "minecraft:ladder": "ladder",
 "minecraft:pointed_dripstone": "pointed_dripstone",
 "minecraft:chain": "chain",
 "minecraft:iron_bars": "iron_bars",
 "minecraft:lightning_rod": "lightning_rod",
 "minecraft:bell": "bell",
 "minecraft:grindstone": "grindstone",
 "minecraft:stonecutter": "stonecutter",
 "minecraft:loom": "loom",
 "minecraft:cartography_table": "cartography_table",
 "minecraft:fletching_table": "fletching_table",
 "minecraft:smithing_table": "smithing_table",
 "minecraft:cauldron": "cauldron",
 "minecraft:composter": "composter",
 "minecraft:beehive": "beehive",
 "minecraft:bee_nest": "bee_nest",
 "minecraft:hay_block": "hay_block",
 "minecraft:melon": "melon_block",
 "minecraft:pumpkin": "pumpkin",
 "minecraft:carved_pumpkin": "carved_pumpkin",
 "minecraft:lectern": "lectern",
 "minecraft:stonecutter": "stonecutter",
 
 // ===== 结构方块 =====
 "minecraft:structure_block": "structure_block",
 "minecraft:structure_void": "structure_void",
 "minecraft:barrier": "barrier",
 "minecraft:command_block": "command_block",
 "minecraft:chain_command_block": "chain_command_block",
 "minecraft:repeating_command_block": "repeating_command_block",
 
 // ===== 末地传送门 =====
 "minecraft:end_portal": "end_portal",
 "minecraft:end_portal_frame": "end_portal_frame",
 "minecraft:portal": "portal",
 
 // ===== 刷怪笼 =====
 "minecraft:spawner": "mob_spawner",
 
 // ===== 酿造台 =====
 "minecraft:brewing_stand": "brewing_stand",
 
 // ===== 花盆 =====
 "minecraft:flower_pot": "flower_pot",
 
 // ===== 头颅 =====
 "minecraft:skull": "skull",
 "minecraft:skeleton_skull": "skeleton_skull",
 "minecraft:wither_skeleton_skull": "wither_skeleton_skull",
 "minecraft:player_head": "player_head",
 "minecraft:zombie_head": "zombie_head",
 "minecraft:creeper_head": "creeper_head",
 "minecraft:dragon_head": "dragon_head",
 "minecraft:skull_wall": "skull_wall",
};

// 旧版ID别名（兼容）
var LEGACY_ALIASES = {
 "minecraft:wooden_slab": "oak_slab",
 "minecraft:tallgrass": "tallgrass",
 "minecraft:reeds": "reeds",
 "minecraft:snow_layer": "snow_layer",
 "minecraft:wall_sign": "wall_sign",
 "minecraft:standing_sign": "standing_sign",
 "minecraft:bed": "bed",
 "minecraft:monster_egg": "monster_egg",
 "minecraft:red_flower": "poppy",
 "minecraft:activator_rail": "activator_rail",
 "minecraft:detector_rail": "detector_rail",
 "minecraft:rail": "rail",
 "minecraft:waterlily": "waterlily",
 "minecraft:web": "web",
 "minecraft:wooden_button": "wooden_button",
 "minecraft:melon_block": "melon_block",
 "minecraft:skull": "skull",
 "minecraft:brewing_stand": "brewing_stand",
 "minecraft:redstone_wire": "redstone_wire",
 "minecraft:nether_brick": "nether_brick",
 "minecraft:red_nether_brick": "red_nether_brick",
 "minecraft:hardened_clay": "hardened_clay",
 "minecraft:portal": "portal",
 "minecraft:double_plant": "double_plant",
 "minecraft:tripwire": "tripwire",
 "minecraft:flower_pot": "flower_pot",
 "minecraft:end_portal_frame": "end_portal_frame",
 "minecraft:end_portal": "end_portal",
 "minecraft:structure_block": "structure_block",
 "minecraft:structure_void": "structure_void",
 "minecraft:lit_redstone_lamp": "redstone_lamp",
 "minecraft:barrier": "barrier",
 "minecraft:powered_repeater": "repeater",
 "minecraft:unlit_redstone_torch": "redstone_torch",
 "minecraft:command_block": "command_block",
 "minecraft:chain_command_block": "chain_command_block",
 "minecraft:repeating_command_block": "repeating_command_block",
 "minecraft:weighted_pressure_plate_heavy": "heavy_weighted_pressure_plate",
 "minecraft:weighted_pressure_plate_light": "light_weighted_pressure_plate",
 "minecraft:carrot": "carrot",
 "minecraft:potato": "potato",
 "minecraft:cake": "cake",
 "minecraft:grass_path": "grass_path",
 "minecraft:deadbush": "deadbush",
 "minecraft:wooden_pressure_plate": "wooden_pressure_plate",
 "minecraft:stone_pressure_plate": "stone_pressure_plate",
 "minecraft:wooden_door": "wooden_door",
 "minecraft:iron_door": "iron_door",
 "minecraft:oak_door": "oak_door",
 "minecraft:spruce_door": "spruce_door",
 "minecraft:birch_door": "birch_door",
 "minecraft:jungle_door": "jungle_door",
 "minecraft:acacia_door": "acacia_door",
 "minecraft:dark_oak_door": "dark_oak_door",
 "minecraft:mangrove_door": "mangrove_door",
 "minecraft:cherry_door": "cherry_door",
 "minecraft:crimson_door": "crimson_door",
 "minecraft:warped_door": "warped_door",
 "minecraft:oak_fence": "oak_fence",
 "minecraft:spruce_fence": "spruce_fence",
 "minecraft:birch_fence": "birch_fence",
 "minecraft:jungle_fence": "jungle_fence",
 "minecraft:acacia_fence": "acacia_fence",
 "minecraft:dark_oak_fence": "dark_oak_fence",
 "minecraft:mangrove_fence": "mangrove_fence",
 "minecraft:cherry_fence": "cherry_fence",
 "minecraft:nether_brick_fence": "nether_brick_fence",
 "minecraft:crimson_fence": "crimson_fence",
 "minecraft:warped_fence": "warped_fence",
 "minecraft:oak_fence_gate": "oak_fence_gate",
 "minecraft:spruce_fence_gate": "spruce_fence_gate",
 "minecraft:birch_fence_gate": "birch_fence_gate",
 "minecraft:jungle_fence_gate": "jungle_fence_gate",
 "minecraft:acacia_fence_gate": "acacia_fence_gate",
 "minecraft:dark_oak_fence_gate": "dark_oak_fence_gate",
 "minecraft:mangrove_fence_gate": "mangrove_fence_gate",
 "minecraft:crimson_fence_gate": "crimson_fence_gate",
 "minecraft:warped_fence_gate": "warped_fence_gate",
 "minecraft:oak_trapdoor": "trapdoor",
 "minecraft:spruce_trapdoor": "trapdoor",
 "minecraft:birch_trapdoor": "trapdoor",
 "minecraft:jungle_trapdoor": "trapdoor",
 "minecraft:acacia_trapdoor": "trapdoor",
 "minecraft:dark_oak_trapdoor": "trapdoor",
 "minecraft:mangrove_trapdoor": "trapdoor",
 "minecraft:iron_trapdoor": "iron_trapdoor",
 "minecraft:crimson_trapdoor": "trapdoor",
 "minecraft:warped_trapdoor": "trapdoor",
 "minecraft:birch_button": "birch_button",
 "minecraft:jungle_button": "jungle_button",
 "minecraft:acacia_button": "acacia_button",
 "minecraft:dark_oak_button": "dark_oak_button",
 "minecraft:mangrove_button": "mangrove_button",
 "minecraft:cherry_button": "cherry_button",
 "minecraft:crimson_button": "crimson_button",
 "minecraft:warped_button": "warped_button",
 "minecraft:polished_blackstone_button": "polished_blackstone_button",
 "minecraft:powered_rail": "powered_rail",
 "minecraft:crafting_table": "crafting_table",
 "minecraft:enchanting_table": "enchanting_table",
 "minecraft:furnace": "furnace",
 "minecraft:lit_furnace": "furnace",
 "minecraft:blast_furnace": "blast_furnace",
 "minecraft:smoker": "smoker",
 "minecraft:anvil": "anvil",
 "minecraft:chipped_anvil": "anvil",
 "minecraft:damaged_anvil": "anvil",
 "minecraft:grindstone": "grindstone",
 "minecraft:stonecutter": "stonecutter",
 "minecraft:lectern": "lectern",
 "minecraft:cartography_table": "cartography_table",
 "minecraft:fletching_table": "fletching_table",
 "minecraft:smithing_table": "smithing_table",
 "minecraft:loom": "loom",
 "minecraft:composter": "composter",
 "minecraft:barrel": "barrel",
 "minecraft:cauldron": "cauldron",
 "minecraft:beacon": "beacon",
 "minecraft:conduit": "conduit",
 "minecraft:ender_chest": "ender_chest",
 "minecraft:shulker_box": "shulker_box",
 "minecraft:white_shulker_box": "white_shulker_box",
 "minecraft:orange_shulker_box": "orange_shulker_box",
 "minecraft:magenta_shulker_box": "magenta_shulker_box",
 "minecraft:light_blue_shulker_box": "light_blue_shulker_box",
 "minecraft:yellow_shulker_box": "yellow_shulker_box",
 "minecraft:lime_shulker_box": "lime_shulker_box",
 "minecraft:pink_shulker_box": "pink_shulker_box",
 "minecraft:gray_shulker_box": "gray_shulker_box",
 "minecraft:light_gray_shulker_box": "light_gray_shulker_box",
 "minecraft:cyan_shulker_box": "cyan_shulker_box",
 "minecraft:purple_shulker_box": "purple_shulker_box",
 "minecraft:blue_shulker_box": "blue_shulker_box",
 "minecraft:brown_shulker_box": "brown_shulker_box",
 "minecraft:green_shulker_box": "green_shulker_box",
 "minecraft:red_shulker_box": "red_shulker_box",
 "minecraft:black_shulker_box": "black_shulker_box",
 "minecraft:mob_spawner": "mob_spawner",
 "minecraft:spawner": "mob_spawner",
};